services:
  coffee-records:
    image: localhost:5000/coffee-records:latest
    container_name: coffee-records
    restart: unless-stopped
    ports:
      - 8181:5000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-192.168.1.91}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-coffee-records}
    volumes:
      - /var/www/html/resources/coffee:/resources
    networks:
      - coffee-net
networks:
  coffee-net:
    driver: bridge

